[supervisord]
nodaemon=true
logfile=/app/supervisor/run/supervisord.log  ; pindah supaya writable

[program:laravel-listener-rest]
command=/usr/local/bin/php /app/artisan serve --host=0.0.0.0 --port=9003
directory=/app
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/app/supervisor/run/listener-rest.log  ; pindah supaya writable

[program:laravel-listener-rest-staging]
command=/usr/local/bin/php /app/artisan serve --host=0.0.0.0 --port=9007
directory=/app
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/app/supervisor/run/listener-rest-staging.log  ; pindah supaya writable
