[program:laravel-scheduler]
process_name=%(program_name)s
command=/bin/bash -c "while true; do /usr/local/bin/php /app/artisan schedule:run --verbose --no-interaction >> /app/supervisor/run/scheduler.log 2>&1; sleep 60; done"
directory=/app
autostart=true
autorestart=true
startsecs=0
startretries=3
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/app/supervisor/run/scheduler.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
