[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log

[program:laravel-listener-rest]
command=/usr/local/bin/php /app/artisan serve --host=0.0.0.0 --port=9003
directory=/app
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/supervisor/listener-rest.log

