[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=/bin/bash /app/docker/bin/wait-for-rabbitmq.sh /usr/local/bin/php /app/artisan queue:work rabbitmq --queue=default,installation,elasticsearch,billing,satusehat,xendit,import,export --sleep=3 --tries=3 --timeout=3600 --max-jobs=100 --max-time=3600 --memory=512 --verbose
directory=/app
autostart=true
autorestart=true
startsecs=10
startretries=9999
user=www-data
numprocs=1
stopwaitsecs=3610
stopsignal=SIGTERM
redirect_stderr=true
stdout_logfile=/app/supervisor/run/worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
