services:
  frankenphp:
    container_name: klinik
    image: laravel-klinik-app
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    entrypoint: php artisan octane:start --server=frankenphp --host=0.0.0.0 --port=${FRANKEN_PORT:-8002} --workers=4 --max-requests=1000
    ports:
      - "${FRANKEN_PORT:-8002}:${FRANKEN_PORT:-8002}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app
    networks:
      - klinik-project
    env_file:
      - .env.production
    environment:
      XDG_CONFIG_HOME: /var/www/html/config 
      XDG_DATA_HOME: /var/www/html/data 

  caddy:
    image: caddy:latest
    container_name: klinik_caddy
    restart: always
    ports:
      - "84:80"    # port host 8081 ke container 80
      - "8443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frankenphp
    networks:
      - klinik-project

networks:
  klinik-project:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: