services:
  wellmed:
    container_name: wellmed-backbone
    image: wellmed-backbone
    build:
      context: .
      dockerfile: ./docker-arm/app/Dockerfile
      target: development
    ports:
      - "${WELLMED_BACKBONE_PORT:-9000}:${WELLMED_BACKBONE_PORT:-9000}"
    volumes:
      - ./repositories:/app/repositories
      - ./app:/app/app
      - ./features:/app/features
      - ./config:/app/config
      - ./public:/app/public
      - ./bootstrap/app.php:/app/bootstrap/app.php
      - ./database:/app/database
      - ./projects/wellmed-backbone:/app/projects/wellmed-backbone
      - ./projects/wellmed-gateway:/app/projects/wellmed-gateway
      - ./routes/api-backbone.php:/app/routes/api.php
      - ./composer_backbone.json:/app/composer.json
      - ./.env.backbone:/app/.env
      - ./docker/conf.d/upload.ini:/usr/local/etc/php/conf.d/upload.ini
      - wellmed_backbone_storage:/app/storage
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000 || exit 1"]
    networks:
      - wellmed-core
    entrypoint: ["/usr/local/bin/entrypoint.backbone.sh"]
    depends_on:
      - wellmed_pgbouncer
    env_file:
      - .env.backbone
    environment:
      APP_ENV: development
      PHP_INI_SCAN_DIR: /usr/local/etc/php/conf.d
      PHP_UPLOAD_MAX_FILESIZE: 100M
      PHP_POST_MAX_SIZE: 100M
      PHP_MEMORY_LIMIT: -1

  wellmed_listener:
    container_name: wellmed-listener
    image: wellmed-listener
    build:
      context: .
      dockerfile: ./docker-arm/app/Dockerfile
      target: development
    volumes:
      - ./repositories:/app/repositories
      - ./app:/app/app
      - ./features:/app/features
      - ./config:/app/config
      - ./public:/app/public
      - ./database:/app/database
      - ./projects/wellmed-backbone:/app/projects/wellmed-backbone
      - ./projects/wellmed-gateway:/app/projects/wellmed-gateway
      - ./routes/api-backbone.php:/app/routes/api.php
      - ./composer_backbone.json:/app/composer.json
      - ./.env.backbone:/app/.env
      - wellmed_backbone_listener:/app/storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - "9003:9003"
    networks:
      - wellmed-core
    entrypoint: ["/usr/local/bin/entrypoint.listener.sh"]   # <— LISTENER MODE (NO OCTANE)
    depends_on:
      - wellmed
      - wellmed_pgbouncer
    env_file:
      - .env.backbone
    environment:
      APP_ENV: development
      PHP_MEMORY_LIMIT: 1024M

  wellmed_hq:
    container_name: wellmed-hq
    image: wellmed-hq
    build:
      context: .
      dockerfile: ./docker/common/Dockerfile-hq
      target: development
    ports:
      - "${WELLMED_HQ_PORT:-9001}:${WELLMED_HQ_PORT:-9001}"
    volumes:
      - ./repositories:/app/repositories
      - ./app:/app/app
      - ./projects/hq:/app/projects/hq
      - ./features:/app/features
      - ./config:/app/config
      - ./public:/app/public
      - ./routes:/app/routes
      - ./database:/app/database
      - ./routes/api-hq.php:/app/routes/api.php
      - ./.env.hq:/app/.env
      - ./composer_hq.json:/app/composer.json
      - wellmed_hq_storage:/app/storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9001 || exit 1"]
    networks:
      - wellmed-core
    entrypoint: ["/usr/local/bin/entrypoint.hq.sh"]
    depends_on:
      - wellmed_pgbouncer
    env_file:
      - .env.hq
    environment:
      APP_ENV: development
      PHP_INI_SCAN_DIR: /usr/local/etc/php/conf.d
      PHP_UPLOAD_MAX_FILESIZE: 10M
      PHP_POST_MAX_SIZE: 10M

  wellmed_pgbouncer:
    container_name: wellmed-pgbouncer
    image: wellmed-pgbouncer-arm
    build:
      context: .
      dockerfile: ./docker-arm/database/Dockerfile
    ports:
      - "6432:6432"
    volumes:
      - ./docker-arm/database/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./docker-arm/database/userlist.txt:/etc/pgbouncer/userlist.txt:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - wellmed-core
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 6432 -U admin_kalpa || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  wellmed-core:
    driver: bridge

volumes:
  wellmed_backbone_storage:
  wellmed_backbone_listener:
  wellmed_hq_storage: