services:
  wellmed_lite:
    container_name: wellmed_lite
    image: wellmed-lite
    build:
      context: .
      dockerfile: ./docker/common/Dockerfile-lite-dev
      target: development
    ports:
      - "${WELLMED_LITE_PORT:-9000}:${WELLMED_LITE_PORT:-9000}"
    volumes:
      - ./repositories:/app/repositories
      - ./app:/app/app
      - ./projects/wellmed-lite:/app/projects/wellmed-lite
      - ./features:/app/features
      - ./config:/app/config
      - ./public:/app/public
      - ./routes/api-lite.php:/app/routes/api.php
      - ./database:/app/database
      - ./.env.lite:/app/.env
      - ./composer_lite.json:/app/composer.json
      - wellmed_lite_storage:/app/storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000 || exit 1"]
    networks:
      - wellmed-core
    entrypoint: ["/usr/local/bin/entrypoint.lite.sh"]
    env_file:
      - .env.lite
    environment:
        PHP_INI_SCAN_DIR: /usr/local/etc/php/conf.d
        PHP_UPLOAD_MAX_FILESIZE: 10M
        PHP_POST_MAX_SIZE: 10M

  wellmed_plus:
    container_name: wellmed_plus
    image: wellmed-plus
    build:
      context: .
      dockerfile: ./docker/common/Dockerfile-plus-dev
      target: development
    ports:
      - "${WELLMED_PLUS_PORT:-9002}:${WELLMED_PLUS_PORT:-9002}"
    volumes:
      - ./repositories:/app/repositories
      - ./app:/app/app
      - ./projects/wellmed-plus:/app/projects/wellmed-plus
      - ./features:/app/features
      - ./config:/app/config
      - ./public:/app/public
      - ./database:/app/database
      - ./.env.plus:/app/.env
      - ./composer_plus.json:/app/composer.json
      - ./routes/api-plus.php:/app/routes/api.php
      - wellmed_plus_storage:/app/storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9002 || exit 1"]
    networks:
      - wellmed-core
    entrypoint: ["/usr/local/bin/entrypoint.plus.sh"]
    env_file:
      - .env.plus
    environment:
        PHP_INI_SCAN_DIR: /usr/local/etc/php/conf.d
        PHP_UPLOAD_MAX_FILESIZE: 10M
        PHP_POST_MAX_SIZE: 10M

  wellmed_hq:
    container_name: wellmed_hq
    image: wellmed-hq
    build:
      context: .
      dockerfile: ./docker/common/Dockerfile-hq
      target: development
    ports:
      - "${WELLMED_HQ_PORT:-9001}:${WELLMED_HQ_PORT:-9001}"
    volumes:
      - ./repositories:/app/repositories
      - ./app:/app/app
      - ./projects/hq:/app/projects/hq
      - ./features:/app/features
      - ./config:/app/config
      - ./public:/app/public
      - ./routes:/app/routes
      - ./database:/app/database
      - ./routes/api-hq.php:/app/routes/api.php
      - ./.env.hq:/app/.env
      - ./composer_hq.json:/app/composer.json
      - wellmed_hq_storage:/app/storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9001 || exit 1"]
    networks:
      - wellmed-core
    entrypoint: ["/usr/local/bin/entrypoint.hq.sh"]
    env_file:
      - .env.hq
    environment:
        PHP_INI_SCAN_DIR: /usr/local/etc/php/conf.d
        PHP_UPLOAD_MAX_FILESIZE: 10M
        PHP_POST_MAX_SIZE: 10M

  wellmed_rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - wellmed-core

networks:
  wellmed-core:
    driver: bridge

volumes:  
  wellmed_lite_storage:
  wellmed_plus_storage:
  wellmed_hq_storage:
  rabbitmq_data:
  # wellmed_hq_storage:
