services:
  frankenphp:
    container_name: klinik
    image: laravel-klinik-app
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    entrypoint: php artisan octane:start --server=frankenphp --host=0.0.0.0 --port=${FRANKEN_PORT:-8002} --workers=4 --max-requests=1000
    ports:
      - "${FRANKEN_PORT:-8002}:${FRANKEN_PORT:-8002}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app
    networks:
      - klinik-project
    env_file:
      - .env
    environment:
      XDG_CONFIG_HOME: /var/www/html/config 
      XDG_DATA_HOME: /var/www/html/data 

networks:
  klinik-project:
    driver: bridge
