services:
  # node:
  #   build:
  #     context: .
  #     dockerfile: ./docker/common/Dockerfile-node
  #   container_name: node-builder
  #   working_dir: /app
  #   volumes:
  #     - ./repositories:/app/repositories
  #     - ./projects:/app/projects
  #     - ./groups:/app/groups
  #     - ./tenants:/app/tenants
  #     - ./public:/app/public
  #     - ./package.json:/app/package.json
  #     - ./package-lock.json:/app/package-lock.json
  #     - ./tsconfig.json:/app/tsconfig.json
  #     - ./tailwind.config.js:/app/tailwind.config.js
  #     - ./tailwind.preset.js:/app/tailwind.preset.js
  #     - ./docker/common/entrypoint.node.sh:/app/entrypoint.node.sh  # <-- mount file ke container
  #     - ./node_modules:/app/node_modules
  #   entrypoint: ["/app/entrypoint.node.sh"]
  #   networks:
  #     - caddy-projects

  wellmed:
    container_name: wellmed-backbone
    image: wellmed-backbone
    build:
      context: .
      dockerfile: ./docker/common/Dockerfile-backbone-dev
      target: development
    ports:
      - "9000:9000"
    volumes:
      - ./repositories:/app/repositories
      - ./app:/app/app
      - ./features:/app/features
      - ./config:/app/config
      - ./public:/app/public
      - ./bootstrap/app.php:/app/bootstrap/app.php
      - ./database:/app/database
      - ./projects/wellmed-backbone:/app/projects/wellmed-backbone
      - ./projects/wellmed-gateway:/app/projects/wellmed-gateway
      - ./routes/api-backbone.php:/app/routes/api.php
      - ./composer_backbone.json:/app/composer.json
      - ./.env.backbone:/app/.env
      - ./docker/conf.d/upload.ini:/usr/local/etc/php/conf.d/upload.ini
      - wellmed_backbone_storage:/app/storage
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000 || exit 1"]
    networks:
      - caddy-projects
    entrypoint: ["/usr/local/bin/entrypoint.backbone.sh"]
    env_file:
      - .env.backbone
    environment:
        PHP_INI_SCAN_DIR: /usr/local/etc/php/conf.d
        PHP_UPLOAD_MAX_FILESIZE: 100M
        PHP_POST_MAX_SIZE: 100M
        PHP_MEMORY_LIMIT: -1

  wellmed_listener:
    container_name: wellmed-listener
    image: wellmed-listener
    build:
      context: .
      dockerfile: ./docker-arm/app/Dockerfile
      target: development
    volumes:
      - ./repositories:/app/repositories
      - ./app:/app/app
      - ./features:/app/features
      - ./config:/app/config
      - ./public:/app/public
      - ./bootstrap/app.php:/app/bootstrap/app.php
      - ./database:/app/database
      - ./projects/wellmed-backbone:/app/projects/wellmed-backbone
      - ./projects/wellmed-gateway:/app/projects/wellmed-gateway
      - ./routes/api-backbone.php:/app/routes/api.php
      - ./composer_backbone.json:/app/composer.json
      - ./.env.backbone:/app/.env
      - ./docker/conf.d/upload.ini:/usr/local/etc/php/conf.d/upload.ini
      - wellmed_backbone_storage:/app/storage
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - "9003:9003"
    networks:
      - caddy-projects
    entrypoint: ["/usr/local/bin/entrypoint.worker.sh"]     # <— WORKER MODE
    depends_on:
      - wellmed
    env_file:
      - .env.backbone

  wellmed_hq:
    container_name: wellmed-hq
    image: wellmed-hq
    build:
      context: .
      dockerfile: ./docker/common/Dockerfile-hq
      target: development
    ports:
      - "9001:9001"
    volumes:
      - ./repositories:/app/repositories
      - ./app:/app/app
      - ./projects/hq:/app/projects/hq
      - ./features:/app/features
      - ./config:/app/config
      - ./public:/app/public
      - ./routes:/app/routes
      - ./database:/app/database
      - ./routes/api-hq.php:/app/routes/api.php
      - ./.env.hq:/app/.env
      - ./composer_hq.json:/app/composer.json
      - wellmed_hq_storage:/app/storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9001 || exit 1"]
    networks:
      - caddy-projects
    entrypoint: ["/usr/local/bin/entrypoint.hq.sh"]
    env_file:
      - .env.hq
    environment:
        PHP_INI_SCAN_DIR: /usr/local/etc/php/conf.d
        PHP_UPLOAD_MAX_FILESIZE: 10M
        PHP_POST_MAX_SIZE: 10M

  wellmed_pgbouncer:
    build:
      context: .
      dockerfile: ./docker/pgbouncer/Dockerfile.local
    container_name: wellmed-pgbouncer-local
    ports:
      - "6432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - caddy-projects
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "psql -h localhost -p 5432 -U postgres -d pgbouncer -c 'SHOW POOLS;' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  caddy-projects:
    external: true

volumes:
  wellmed_backbone_storage:
  wellmed_backbone_listener:
  wellmed_hq_storage:
  # wellmed_hq_storage:
