services:
  wellmed_lite:
    container_name: wellmed_lite
    image: wellmed-lite
    build:
      context: .
      dockerfile: ./docker/common/Dockerfile-lite
      target: development
    ports:
      - "${WELLMED_LITE_PORT:-9000}:${WELLMED_LITE_PORT:-9000}"
    volumes:
      - ./repositories:/app/repositories
      - ./app:/app/app
      - ./projects/wellmed-lite:/app/projects/wellmed-lite
      - ./features:/app/features
      - ./config:/app/config
      - ./public:/app/public
      - ./routes:/app/routes
      - ./database:/app/database
      - ./composer_lite.json:/app/composer.json
      - wellmed_lite_storage:/app/storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000 || exit 1"]
    networks:
      - caddy-projects
    entrypoint: ["/usr/local/bin/entrypoint.lite.sh"]
    env_file:
      - .env.lite
    environment:
        PHP_INI_SCAN_DIR: /usr/local/etc/php/conf.d
        PHP_UPLOAD_MAX_FILESIZE: 10M
        PHP_POST_MAX_SIZE: 10M
    #   XDG_CONFIG_HOME: /var/www/html/config
    #   XDG_DATA_HOME: /var/www/html/data

  # wellmed_hq:
  #   container_name: wellmed_hq
  #   image: wellmed-hq
  #   build:
  #     context: .
  #     dockerfile: ./docker/common/Dockerfile-hq
  #     target: development
  #     # args:
  #     #   XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
  #     #   XDEBUG_MODE: develop,coverage,debug,profile
  #     #   XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
  #     #   XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
  #     #   XDEBUG_LOG: /dev/stdout
  #     #   XDEBUG_LOG_LEVEL: 0
  #   ports:
  #     - "${WELLMED_HQ_PORT:-8007}:${WELLMED_HQ_PORT:-8007}"
  #   volumes:
  #     - ./repositories:/app/repositories
  #     - ./app:/app/app
  #     - ./projects/hq:/app/projects/hq
  #     - ./config:/app/config
  #     - ./public:/app/public
  #     - ./routes:/app/routes
  #     - ./database:/app/database
  #     - ./composer_hq.json:/app/composer.json
  #     - wellmed_hq_storage:/app/storage
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   restart: unless-stopped
  #   networks:
  #     - caddy-projects
  #   entrypoint: ["/usr/local/bin/entrypoint.hq.sh"]
  #   env_file:
  #     - .env.hq
  #   # environment:
  #   #   XDG_CONFIG_HOME: /var/www/html/config
  #   #   XDG_DATA_HOME: /var/www/html/data
  #   # command: >
  #   #   php artisan octane:frankenphp
  #   #   --host=0.0.0.0
  #   #   --port=${WELLMED_HQ_PORT:-8007}
  #   #   --admin-port=9007
  #   #   --workers=${PHP_CLI_SERVER_WORKERS:-2}
  #   #   --max-requests=1000

networks:
  caddy-projects:
    external: true

volumes:  
  wellmed_lite_storage:
  # wellmed_hq_storage:
