services:
  wellmed:
    container_name: wellmed-backbone
    image: wellmed-backbone
    build:
      context: .
      dockerfile: ./docker/common/Dockerfile-backbone-dev
      target: development
    ports:
      - "${WELLMED_BACKBONE_PORT:-9000}:${WELLMED_BACKBONE_PORT:-9000}"
    volumes:
      - ./repositories:/app/repositories
      - ./app:/app/app
      - ./features:/app/features
      - ./config:/app/config
      - ./public:/app/public
      - ./database:/app/database
      - ./projects/wellmed-backbone:/app/projects/wellmed-backbone
      - ./projects/wellmed-gateway:/app/projects/wellmed-gateway
      - ./routes/api-backbone.php:/app/routes/api.php
      - ./composer_backbone.json:/app/composer.json
      - ./.env.backbone:/app/.env
      - wellmed_backbone_storage:/app/storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000 || exit 1"]
    networks:
      - wellmed-core
    entrypoint: ["/usr/local/bin/entrypoint.backbone.sh"]
    env_file:
      - .env.backbone
    environment:
        PHP_INI_SCAN_DIR: /usr/local/etc/php/conf.d
        PHP_UPLOAD_MAX_FILESIZE: 10M
        PHP_POST_MAX_SIZE: 10M

  wellmed_listener:
    container_name: wellmed-listener
    image: wellmed-backbone
    volumes:
      - ./repositories:/app/repositories
      - ./app:/app/app
      - ./features:/app/features
      - ./config:/app/config
      - ./public:/app/public
      - ./database:/app/database
      - ./projects/wellmed-backbone:/app/projects/wellmed-backbone
      - ./projects/wellmed-gateway:/app/projects/wellmed-gateway
      - ./routes/api-backbone.php:/app/routes/api.php
      - ./composer_backbone.json:/app/composer.json
      - ./.env.backbone:/app/.env
      - wellmed_backbone_listener:/app/storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - "9003:9003"
    networks:
      - wellmed-core
    entrypoint: ["/usr/local/bin/entrypoint.worker.sh"]     # <— WORKER MODE
    depends_on:
      - wellmed
    env_file:
      - .env.backbone

  wellmed_hq:
    container_name: wellmed-hq
    image: wellmed-hq
    build:
      context: .
      dockerfile: ./docker/common/Dockerfile-hq
      target: development
    ports:
      - "${WELLMED_HQ_PORT:-9001}:${WELLMED_HQ_PORT:-9001}"
    volumes:
      - ./repositories:/app/repositories
      - ./app:/app/app
      - ./projects/hq:/app/projects/hq
      - ./features:/app/features
      - ./config:/app/config
      - ./public:/app/public
      - ./routes:/app/routes
      - ./database:/app/database
      - ./routes/api-hq.php:/app/routes/api.php
      - ./.env.hq:/app/.env
      - ./composer_hq.json:/app/composer.json
      - wellmed_hq_storage:/app/storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9001 || exit 1"]
    networks:
      - wellmed-core
    entrypoint: ["/usr/local/bin/entrypoint.hq.sh"]
    env_file:
      - .env.hq
    environment:
        PHP_INI_SCAN_DIR: /usr/local/etc/php/conf.d
        PHP_UPLOAD_MAX_FILESIZE: 10M
        PHP_POST_MAX_SIZE: 10M

  wellmed_rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - wellmed-core

networks:
  wellmed-core:
    driver: bridge

volumes:  
  wellmed_backbone_storage:
  wellmed_backbone_listener:
  wellmed_hq_storage:
  redis_data:
  pgsql_data:
  rabbitmq_data: