services:
  wellmed_franken:
    container_name: wellmed
    image: wellmed-app
    build:
      context: .
      dockerfile: ./docker/common/Dockerfile
      target: development
      args:
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    ports:
      - "${FRANKEN_PORT:-8004}:${FRANKEN_PORT:-8004}"
    volumes:
      - ./repositories:/app/repositories:cached
      - ./app:/app/app:cached
      - ./projects/klinik:/app/projects/klinik:cached
      - ./groups:/app/groups:cached
      - ./config:/app/config:cached
      - ./tenants:/app/tenants:cached
      - ./public:/app/public:cached
      - wellmed_storage:/app/storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - caddy-projects
    env_file:
      - .env
    environment:
      XDG_CONFIG_HOME: /var/www/html/config
      XDG_DATA_HOME: /var/www/html/data
    command: >
      php artisan octane:frankenphp
      --host=0.0.0.0
      --port=${FRANKEN_PORT:-8004}
      --workers=${PHP_CLI_SERVER_WORKERS:-4}
      --max-requests=1000

  wellmed_lite:
    container_name: wellmed_lite
    image: wellmed-lite
    build:
      context: .
      dockerfile: ./docker/common/Dockerfile-lite
      target: development
      args:
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    ports:
      - "${WELLMED_LITE_PORT:-8005}:${WELLMED_LITE_PORT:-8005}"
    volumes:
      - ./repositories:/app/repositories:cached
      - ./app:/app/app:cached
      - ./projects/wellmed-lite:/app/projects/wellmed-lite:cached
      - ./groups:/app/groups:cached
      - ./config:/app/config:cached
      - ./tenants:/app/tenants:cached
      - ./public:/app/public:cached
      - ./database:/app/database:cached
      - wellmed_lite_storage:/app/storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - caddy-projects
    env_file:
      - .env.lite
    environment:
      XDG_CONFIG_HOME: /var/www/html/config
      XDG_DATA_HOME: /var/www/html/data
    command: >
      php artisan octane:frankenphp
      --host=0.0.0.0
      --port=${WELLMED_LITE_PORT:-8005}
      --workers=${PHP_CLI_SERVER_WORKERS:-4}
      --max-requests=1000


networks:
  caddy-projects:
    external: true

volumes:  
  wellmed_storage:
  wellmed_lite_storage:
