services:
  klinik_franken:
    container_name: klinik
    image: klinik-app
    build:
      context: .
      dockerfile: ./docker/common/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    ports:
      - "${FRANKEN_PORT:-8004}:${FRANKEN_PORT:-8004}"
    volumes:
      - ./repositories:/app/repositories:cached
      - ./app:/app/app:cached
      - ./projects/klinik:/app/projects/klinik:cached
      - ./groups:/app/groups:cached
      - ./tenants:/app/tenants:cached
      - klinik_storage:/app/storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - caddy-projects
    env_file:
      - .env
    environment:
      XDG_CONFIG_HOME: /var/www/html/config
      XDG_DATA_HOME: /var/www/html/data
    user: "${UID:-1000}:${GID:-1000}"
    command: >
      php artisan octane:frankenphp
      --host=0.0.0.0
      --port=${FRANKEN_PORT:-8004}
      --workers=${PHP_CLI_SERVER_WORKERS:-4}
      --max-requests=1000

networks:
  caddy-projects:
    external: true

volumes:  
  klinik_storage:
