[unix_http_server]
file=/app/supervisor/run/supervisor.sock   ; pindah dari /var/run
chmod=0700
chown=www-data:www-data

[supervisord]
nodaemon=true
logfile=/app/supervisor/run/supervisord.log  ; pindah log supaya writable
pidfile=/app/supervisor/run/supervisord.pid  ; pindah PID file

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///app/supervisor/run/supervisor.sock  ; ikut pindah

[include]
files = /etc/supervisor/conf.d/*.conf
